all:
  children:
    group1:
      hosts:
        haproxy-keepalived:
          ansible_host: "{{ host }}"
          ansible_user: "{{ user }}"
          ansible_ssh_private_key_file: "{{ path_to_key }}"
          # ansible_ssh_pass: you_pass
          # ansible_ssh_passphrase: ssh_key_pass
          # ansible_become_pass: you_sudo_pass
    # local:
    #   hosts:
    #     localhost:
    #       ansible_connection: local
